"""Backward-compatible exports for core base handler utilities."""

from .core.base_handler import (
    BaseDiagramHandler,
    MODIFICATION_INNER_REQUIRED,
    MODIFICATION_REQUIRED,
    SINGLE_CLASS_OPTIONAL,
    SINGLE_CLASS_REQUIRED,
    SINGLE_OBJECT_OPTIONAL,
    SINGLE_OBJECT_REQUIRED,
    SINGLE_STATE_OPTIONAL,
    SINGLE_STATE_REQUIRED,
    SYSTEM_CLASS_OPTIONAL,
    SYSTEM_CLASS_REQUIRED,
    SYSTEM_OBJECT_OPTIONAL,
    SYSTEM_OBJECT_REQUIRED,
    SYSTEM_STATE_OPTIONAL,
    SYSTEM_STATE_REQUIRED,
    validate_spec,
)

__all__ = [
    "BaseDiagramHandler",
    "validate_spec",
    "SINGLE_CLASS_REQUIRED",
    "SINGLE_CLASS_OPTIONAL",
    "SYSTEM_CLASS_REQUIRED",
    "SYSTEM_CLASS_OPTIONAL",
    "SINGLE_OBJECT_REQUIRED",
    "SINGLE_OBJECT_OPTIONAL",
    "SYSTEM_OBJECT_REQUIRED",
    "SYSTEM_OBJECT_OPTIONAL",
    "SINGLE_STATE_REQUIRED",
    "SINGLE_STATE_OPTIONAL",
    "SYSTEM_STATE_REQUIRED",
    "SYSTEM_STATE_OPTIONAL",
    "MODIFICATION_REQUIRED",
    "MODIFICATION_INNER_REQUIRED",
]
